#!/usr/bin/env bash

bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 6 7 8 9 0

xrandr --output DisplayPort-0 --right-of HDMI-A-0 --mode 2560x1440 --primary

killall polybar
polybar top-left -r &
polybar bspwm2 -r &

feh --bg-fill ~/Pictures/squares.png

# the system is booting
if [[ $1 != "--reload" ]]; then

  sxhkd &
  unclutter --timeout 3 &
  kdeconnect-indicator &
  picom --daemon --backend glx --config ~/.config/picom/picom.conf




  # required for idea
  wmname compiz
fi


# disable sleep
xset -dpms s off
# disable mouse accel
xset m 1 1

# keyboard
setxkbmap -option 'grp:alt_shift_toggle' -layout us,gr
numlockx on

bspc config window_gap 8
bspc config split_ratio 0.52
bspc config border_width 0
bspc config single_monocle true
bspc config gapless_monocle false
bspc config honor_size_hints true
bspc config borderless_monocle false
bspc config focus_follows_pointer true
bspc config automatic_scheme alternate

bspc rule -a Gimp state=floating follow=on

notify-send "bspwm" "done!"

if [[ $1 != "--reload" ]]; then
  bspc desktop -a 1
  alacritty &
  sleep 0.2
  bspc node -t pseudo_tiled
fi

