#!/usr/bin/env bash

LEFT=HDMI-A-0
RIGHT=DisplayPort-0
bspc monitor $LEFT -d 1 2 3 4 5
bspc monitor $RIGHT -d 6 7 8 9 0

xrandr --output $LEFT --mode 1920x1080 --left-of DisplayPort-0
xrandr --output $RIGHT --mode 2560x1440 --primary

killall polybar
polybar top-left -r &
polybar bspwm2 -r &

if [[ $1 != "--reload" ]]; then
  # the system is booting
  feh --bg-fill ~/Pictures/squares.png

  sxhkd &
  unclutter --timeout 3 &
  kdeconnect-indicator &
  picom --config ~/.config/picom/picom.conf -b

  # disable sleep
  xset -dpms s off

  # disable mouse accel
  xset m 1 1

  # keyboard
  setxkbmap -option 'grp:alt_shift_toggle' -layout us,gr
  numlockx

  # ~/.scripts/toggle-colorscheme

  # required for idea
  wmname compiz
fi

bspc config window_gap 4
bspc config split_ratio 0.52
bspc config border_width 0
bspc config single_monocle true
bspc config gapless_monocle false
bspc config honor_size_hints true
bspc config borderless_monocle false
bspc config focus_follows_pointer true
bspc config automatic_scheme alternate

bspc rule -a Gimp state=floating follow=on

notify-send "bspwm" "done!"

if [[ $# -eq 0 ]]; then
  st &
  sleep 0.2
  bspc node -t pseudo_tiled
fi
