#!/usr/bin/env bash

ws1=" "
ws2=" "
ws3=" "
ws4=" "
ws5=" "
ws6=" "
ws7=" "
ws8=" "
bspc monitor -d $ws1 $ws2 $ws3 $ws4 $ws5 $ws6 $ws7 $ws8

if [[ $1 != "--reload" ]]; then
    sxhkd &
    compton &
    mpd
    polybar bspwm -r &
    unclutter --timeout 3 &


    # keyboard
    setxkbmap -option 'grp:alt_shift_toggle' -layout us,gr
    numlockx

    theme -r

    # Set the border colors.
    . "${HOME}/.cache/wal/colors.sh"
    bspc config normal_border_color   "$color0"
    bspc config active_border_color   "$color3"
    bspc config focused_border_color  "$color3"
    bspc config presel_feedback_color "$color1"
fi


bspc config window_gap              10
bspc config split_ratio           0.52
bspc config border_width             2
bspc config single_monocle        true
bspc config gapless_monocle       false
bspc config honor_size_hints      true
bspc config borderless_monocle    false
bspc config focus_follows_pointer true
bspc config automatic_scheme alternate

bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a Firefox desktop='^2'

notify-send "bspwm" "done!"


if [[ $# -eq 0 ]]; then
    st & 
    sleep 0.2
    bspc node -t pseudo_tiled
fi
