#!/usr/bin/env bash

ws1=" "
ws2=" "
ws3=" "
ws4=" "
ws5=" "
ws6=" "
ws7=" "
ws8=" "

bspc monitor -d I II III IV V VI VII VIII IX X

if [[ $1 != "--reload" ]]; then
    sxhkd &
    compton &
    # mpd
    polybar bspwm -r &
    unclutter --timeout 3 &
    feh --bg-center ~/Pictures/wallhaven-96w8e8.png

    # disable mouse accel
    xset m 1 1


    # keyboard
    setxkbmap -option 'grp:alt_shift_toggle' -layout us,gr
    numlockx

    # Set the border colors.
    bspc config normal_border_color   "#31343f"
    bspc config active_border_color   "#80bbfe"
    bspc config focused_border_color  "#e19ef5"
    bspc config presel_feedback_color "#f9867b"

    # Red Colors
    bspc config normal_border_color   "#010D12"
    bspc config active_border_color   "#A9132A"
    bspc config focused_border_color  "#CB1B32"
    bspc config presel_feedback_color "#363649"


    # required for idea
    wmname compiz

fi


bspc config window_gap              10
bspc config split_ratio           0.52
bspc config border_width             2
bspc config single_monocle        true
bspc config gapless_monocle       false
bspc config honor_size_hints      true
bspc config borderless_monocle    false
bspc config focus_follows_pointer true
bspc config automatic_scheme alternate

bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Chromium desktop='^2'
bspc rule -a Steam desktop='^3'

notify-send "bspwm" "done!"


if [[ $# -eq 0 ]]; then
    st & 
    sleep 0.2
    bspc node -t pseudo_tiled
fi
