#!/usr/bin/env bash

bspc monitor HDMI-A-0 -d 6 7 8 9 0
bspc monitor DisplayPort-0 -d 1 2 3 4 5

xrandr --output HDMI-A-0 --mode 2560x1440
# xrandr --output HDMI-A-0 --mode 1920x1080

function set-borders { 
    color=`xrdb -query | grep "\*.color2" | cut -f 2`
    bspc config normal_border_color   "$color"
    bspc config active_border_color   "$color"
    bspc config focused_border_color  "$color"
    bspc config presel_feedback_color "$color"
}

if [[ $1 != "--reload" ]]; then
    dunst &
    # wal -R
    feh --bg-fill ~/Pictures/otherthing.jpg
    sxhkd &
    compton --config ~/.config/compton/compton.conf &
    mpd
    mpc stop
    polybar bspwm -r &
    polybar bspwm2 -r &
    unclutter --timeout 3 &

    # disable sleep
    xset -dpms s off

    # disable mouse accel
    xset m 1 1


    # keyboard
    setxkbmap -option 'grp:alt_shift_toggle' -layout us,gr
    numlockx


    # Red Colors
    # bspc config normal_border_color   "#010D12"
    # bspc config active_border_color   "#A9132A"
    # bspc config focused_border_color  "#CB1B32"
    # bspc config presel_feedback_color "#363649"


    # required for idea
    wmname compiz

fi


bspc config window_gap              10
bspc config split_ratio           0.52
# bspc config border_width           2
bspc config single_monocle        true
bspc config gapless_monocle       false
bspc config honor_size_hints      true
bspc config borderless_monocle    false
bspc config focus_follows_pointer true
bspc config automatic_scheme alternate

bspc rule -a Gimp state=floating follow=on

notify-send "bspwm" "done!"


if [[ $# -eq 0 ]]; then
    st & 
    sleep 0.2
    bspc node -t pseudo_tiled
fi
