#!/bin/sh

ICON=""
FAILURE=""


function print-failure {
	if [[ $? -ne 0 ]]; then
		echo "$FAILURE Unable to Backup $1"
		exit
	fi
}

echo "$ICON Backup in progress..."

echo "$ICON Music -> onedrive"
rclone sync -P "/run/media/maru/files/Music/" "onedrive:/music/" > /dev/null
print-failure "Music"


echo "$ICON onedrive -> Images"
rclone sync -P "onedrive:/nick/camera" "/run/media/maru/files/Εικόνες/phone" > /dev/null
print-failure "Download Images"

echo "$ICON notes -> onedrive"
rclone copy -P "/home/maru/Documents/obsidian/" "onedrive:/notes/obsidian" > /dev/null
print-failure "Obsidian"

echo " $(date +%d/%m)"
