#!/usr/bin/env bash

package=$(pacaur -Ssq $1 | fzf)
echo "Enter description for package $package: "
read -e desc
line="        $package # $desc"
pacaur -S "$package"

if [[ $? -ne 0 ]] || [[ $2 != "-s" ]]; then
    exit
fi
linum=`cat ~/.scripts/setup | grep "Misc" -n | cut -d":" -f1`
sed -i "72s/.*/&\n$line/" .scripts/setup
