#!/usr/bin/env bash

if [[ $1 == "" ]] || [[ $# -lt 1 ]]; then
    echo "error: no input specified"
    exit
fi

package=$(pacaur -Ssq $1 | fzf)
if [[ $package == "" ]]; then
    exit
fi

pacaur -S "$package"

if [[ $2 != "-s" ]]; then
    exit
fi

echo "Enter description for package $package: "
read -e desc
line="        $package # $desc"

if [[ $? -ne 0 ]] || [[ $2 != "-s" ]]; then
    exit
fi
linum=`cat ~/.scripts/setup | grep "Misc" -n | cut -d":" -f1`
sed -i "72s/.*/&\n$line/" ~/.scripts/setup
