#!/bin/bash
pushd ~ > /dev/null

title="Install Script"

# Install pacaur for AUR
sudo pacman -S yay --needed 

notify-send "$title" "Installed yay"

# Update the system packages
yay -Syu # Update

notify-send "$title" "Updated packages!"

if [[ `command -v st` == "" ]]; then
    git clone https://github.com/nlsnightmare/st
    cd st
    sudo make install
    cd ..
    rm -rf st

    notify-send "$title" "st installed!"
fi

export install_targets=(
        # Windows manager
        i3-gaps

        # Editors
        neovim             # NeoVim
        xclip
        emacs            # Emacs

        # Theaming
        neofetch           # Display system info on terminal
        rxvt-unicode-pixbuf# Terminal emulator
        zsh                # Zsh shell
        feh                # Change desktop background
        dmenu2             # Application launcher
        rofi               # Another Application launcher
        ttf-font-awesome   # Icons for workspaces and more
        cava               # Terminal-based visualizer
        playerctl          # Controll music from the terminal
        w3m                # Display images on terminal
        numlockx           # Enable nums lock on startup
        polybar            # Better status bar
        arduino            # Arduino
        python-pywal       # Generate colorscheme from images
        notify-send        # Create notifications
        compton            # Transparency and more
        unclutter          # Hide mouse when idle
        dunst

    	# Keyboard
        openrazer-meta     # Needed for Razer Keyboard Color control
        razercommander-git # Needed for Razer Keyboard Color control
        linux-headers      # Needed for Razer Keyboard Color control

        # Programming
        rustup             # Rustlang
        nodejs             # Javascript
        npm                # Javascript
        composer           # PHP

        # Services
        systemctl
        mariadb
        apache

        # C/C++
        clang
        cmake 

        # Misc
        aseprite         # Pixel Art Editor
        sl               # Yay! trains!
        tree             # Shows a tree of things
        ranger-git       # CLI file browser
        mpd              # Music Player Daemon
        mpc              # MPD CLI client
        ncmpcpp          # MPD client 
        normalize        # Normalize audio
)

yay -S ${install_targets[*]} --noconfirm --needed


notify-send "$title" "pacaur finished installing packages!"
exit

sudo sed -i "s/Antergos/Arch/g" /etc/os-release
sudo sed -i "s/\;extension=mysqli/extension=mysqli/" /etc/php/php.ini
sudo sed -i "s/\;extension=pdo_mysql/extension=pdo_mysql/" /etc/php/php.ini


systemctl enable mariadb.service
systemctl start  mariadb.service

systemctl enable httpd.service
systemctl start  httpd.service

composer global require laravel/installer


# Make git remember crendentials for one hour
git config --global credential.helper 'cache --timeout=3600'


# Allow user access to arduino etc.
sudo gpasswd -a $USER uucp
sudo gpasswd -a $USER lock
sudo gpasswd -a $USER input
sudo gpasswd -a $USER plugdev

rustup install stable
rustup default stable
rustup toolchain install nightly
rustup component add rust-src
cargo install racer

notify-send "$title" "Rust installed!"

# Javascript autocompletion
sudo npm i -g ternjs
sudo npm i -g live-server
sudo npm i -g eslint


notify-send "$title" "npm packages installed!"

# Needed for python autocompletion
sudo pip install jedi autopep8 flake8 yapf

# Needed for neovim python support
sudo pip install pynvim

# Needed for arduino coms
sudo pip install pyserial

notify-send "$title" "pip packages installed!"

# requires user input
if [[ ! -d ~/.oh-my-zsh ]]; then
    sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

    cd ~/.oh-my-zsh/custom/plugins
    git clone git://github.com/zsh-users/zsh-syntax-highlighting.git
fi

if [[ ! -d ~/.emacs.d ]]; then
    mkdir ~/Documents/Agenda
    git clone https://github.com/nlsnightmare/.emacs.d
    rm ~/.emacs
fi

if [[ ! -d ~/.fzf ]]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install --all
fi

nvim +PlugInstall +UpdateRemotePlugins +qa

# restore last dir
popd > /dev/null
notify-send "$title" "install finised!"
