#!/bin/bash
pushd ~ > /dev/null


title="Install Script"

# Install pacaur for AUR
sudo pacman -S pacaur --needed 

notify-send "$title" "Installed pacaur"

# Update the system packages
pacaur -Syu # Update

notify-send "$title" "Updated packages!"

export install_targets=(
        # Windows manager
        i3-gaps

        # Editors
        neovim             # NeoVim
        xclip
        emacs            # Emacs

        # Theaming
        neofetch           # Display system info on terminal
        rxvt-unicode-pixbuf# Terminal emulator
        zsh                # Zsh shell
        feh                # Change desktop background
        rofi               # Application launcher
        ttf-font-awesome   # Icons for workspaces and more
        cava               # Terminal-based visualizer
        playerctl          # Controll music from the terminal
        cmus               # CLI music player
        w3m                # Display images on terminal
        numlockx           # Enable nums lock on startup
        polybar            # Better status bar
        arduino            # Arduino
        python-pywal       # Generate colorscheme from images
        notify-send        # Create notifications
        compton            # Transparency and more
        unclutter          # Hide mouse when idle
        dunst

    	# Keyboard
        openrazer-meta     # Needed for Razer Keyboard Color control
        razercommander-git # Needed for Razer Keyboard Color control
        linux-headers      # Needed for Razer Keyboard Color control

        hsetroot           # Tile, tint wallpapers & more

        # Programming
        rustup             # Rustlang
        nodejs
        npm
        composer

        # Services
        systemctl
        mariadb
        apache

        # Ruby
        ruby              
        ruby-docs
        ruby-rdoc

        clang
        cmake 

        # Misc
        android-studio # Create android apps
        urxvt-resize-font-git # Change urxvt font size on the fly
        youtube-dl-git   # Download from youtube
        sl               # Yay! trains!
        tree             # Shows a tree of things
        ranger-git       # CLI file browser
        krita            # Image editor
        mpd              # Music Player Daemon
        mpc              # MPD CLI client
        ncmpcpp          # MPD client 
        normalize        # Normalize audio
)

pacaur -S ${install_targets[*]} --noconfirm --noedit --needed


notify-send "$title" "pacaur finished installing packages!"

sudo sed -i "s/Antergos/Arch/g" /etc/os-release
sudo sed -i "s/\;extension=mysqli/extension=mysqli/" /etc/php/php.ini
sudo sed -i "s/\;extension=pdo_mysql/extension=pdo_mysql/" /etc/php/php.ini


systemctl enable mariadb.service
systemctl start  mariadb.service

systemctl enable httpd.service
systemctl start  httpd.service

composer global require laravel/installer


# Make git remember crendentials for one hour
git config --global credential.helper 'cache --timeout=3600'


# Allow user access to arduino etc.
sudo gpasswd -a $USER uucp
sudo gpasswd -a $USER lock
sudo gpasswd -a $USER input
sudo gpasswd -a $USER plugdev

rustup install stable
rustup default stable
rustup toolchain install nightly
rustup component add rust-src
cargo install racer

notify-send "$title" "Rust installed!"

# Javascript autocompletion
sudo npm i -g ternjs
sudo npm i -g live-server
sudo npm i -g eslint


notify-send "$title" "npm packages installed!"

# Needed for python autocompletion
sudo pip install jedi autopep8 flake8 yapf

# Needed for neovim python support
sudo pip install pynvim

# Needed for arduino coms
sudo pip install pyserial

notify-send "$title" "pip packages installed!"

# Install jekyll
gem update
gem install jekyll bundler

notify-send "$title" "Jekyll installed!"


# requires user input
if [[ ! -d ~/.oh-my-zsh ]]; then
    sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

    cd ~/.oh-my-zsh/custom/plugins
    git clone git://github.com/zsh-users/zsh-syntax-highlighting.git
fi

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

if [[ ! -d ~/.emacs.d ]]; then
    mkdir ~/Documents/Agenda
    git clone https://github.com/nlsnightmare/.emacs.d
    rm ~/.emacs
fi

if [[ ! -d ~/.fzf ]]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install --all
fi

nvim +PlugInstall +UpdateRemotePlugins +qa

# restore last dir
popd > /dev/null
echo "done! however, some things are not installed."
echo "namely: st, dwm, dmenu"
