#!/usr/bin/env bash

if [[ $# -ne 1 ]]; then
    echo "usage: `basename $0` [ file | -r ]"
    exit 1
fi

if [[ $1 == '-r' ]] || [[ $1 == '--random' ]]; then
    path=`find ~/Pictures/ ! -path "$HOME/Pictures/Screenshots*" ! -path "$HOME/Pictures/memes*" | sort -R | tail -1`
else
    path=$1
fi

wal -i "$path" > /dev/null 2>&1

if [[ $? -ne 0 ]]; then
    echo "Couldn't generate pallete for '$path'"  
    echo "Delete it? (y/N)"
    read -sn1 opt
    if [[ $opt == 'Y' ]] || [[ $opt == 'y' ]]; then
        rm "$path";
        $0 -r
    fi
    exit;
fi

pkill -USR1 cava
killall dunst &> /dev/null
dunst &> /dev/null &


. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color3"

bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color1"

keyboard "#$color3"
lstrip "#$color3"

echo "primary color: $color3"
exit

clear
neofetch 

notify-send "Theme Changed!"
