#!/usr/bin/python3
import sys
import serial

if len(sys.argv) != 2:
    print("usage: strip [color|mode]")
    exit()

arg = sys.argv[1]

# Initialize led strip
strip = serial.Serial(dsrdtr=False)
strip.setDTR(False)
strip.baudrate = 9600

for i in range(0, 10):
    strip.port = "/dev/ttyACM" + str(i)
    # print("trying port " + strip.port)
    try:
        strip.open()
        break
    except Exception:
        pass


strip.write(bytes(arg, "utf-8"))
