#!/bin/bash
# nice colors: 
# cherry: ff030f

scripts_directory=~/.scripts/colors
wallpapers_directory=~/Pictures/wallpapers

options=("red" "green" "blue" "grey" "crimson" "purple" "rainbow" "ambient" "off" "showoff")

if [[ "$#" -ne 1 ]]; then
    for option in ${options[@]}; do
        echo $option
    done

elif [[ $1 == "showoff" ]]; then
    for option in ${options[@]}; do
        mode $option
        sleep 2
    done

elif [[ $1 == "off" ]]; then
    $scripts_directory/keyboard "#000000"
    $scripts_directory/strip "#000000"
elif [[ $1 == "crimson" ]]; then
    $scripts_directory/keyboard "#ff0022"
    $scripts_directory/strip "#ff0022"
    wal -i ~/Pictures/Cool/crimson.png -b "#0f0d0d" -q
elif [[ $1 == "red" ]]; then
    $scripts_directory/keyboard "#ff0000"
    $scripts_directory/strip "#ff0000"
    hsetroot -full $wallpapers_directory/$1.png
elif [[ $1 == "green" ]]; then
    $scripts_directory/keyboard "#00FF00"
    $scripts_directory/strip "#00FF00"
    wal -i ~/Pictures/Cool/green.png -q
elif [[ $1 == "blue" ]]; then
    $scripts_directory/keyboard "#0012ff"
    $scripts_directory/strip "#0012ff"
    wal -i ~/Pictures/space-2.jpg -q
elif [[ $1 == "grey" ]]; then
    $scripts_directory/keyboard "#ffffff"
    $scripts_directory/strip "#ffffff"
    hsetroot -full $wallpapers_directory/$1.jpg
elif [[ $1 == "purple" ]]; then
    $scripts_directory/keyboard "#ff03ff"
    $scripts_directory/strip "#ff03ff"
    wal -i ~/Pictures/space.jpg -q
elif [[ $1 == "rainbow" ]]; then
    $scripts_directory/strip "R"
    $scripts_directory/keyboard "rainbow"
    wal -i ~/Pictures/Cool/rainbow.jpg -b "#001122" -q
elif [[ $1 == "ambient" ]]; then
    $scripts_directory/strip "A"
    $scripts_directory/keyboard "ambient"
else
    $scripts_directory/strip "$1"
    $scripts_directory/keyboard "$1"
    hsetroot -tile $wallpapers_directory/pattern.jpg -tint "$1"
fi
